stages:
  - lint
  - test

server-go-lint:
  stage: lint
  script:
    - cd server
    - docker build -t stormtask_image_lint -f server/Dockerfile.lint .
    - docker run stormtask_image_lint
    - docker wait stormtask_image_lint

server-go-test:
  stage: test
  image: docker/compose:latest
  services:
  - docker:dind
  script:
  - docker-compose -f docker/compose_test.yaml -p stormtask_compose_test up
  - docker wait stormtask_image_test