stages:
  - lint
  - test

server-go-lint:
  stage: lint
  image: docker
  services:
  - docker:dind
  script:
    - cd server
    - docker build -t stormtask_lint_image -f Dockerfile.lint .
    - docker run stormtask_lint_image

server-go-test:
  stage: test
  image: docker/compose:latest
  services:
  - docker:dind
  script:
  - cd server
  - docker build -t stormtask_test_image -f Dockerfile.test .
  - cd ..
  - docker-compose -f docker/compose_test.yaml -p stormtask_compose_test up --exit-code-from test
