stages:
  - lint
  - test

server-go-lint:
  stage: lint
  image: docker/compose:latest
  services:
  - docker:dind
  script:
    - docker-compose -f docker/compose_lint.yaml -p stormtask_compose_lint up -d --exit-code-from lint

server-go-test:
  stage: test
  image: docker/compose:latest
  services:
  - docker:dind
  script:
  - docker build -t stormtask_test_image -f Dockerfile .
  - docker-compose -f docker/compose_test.yaml -p stormtask_compose_test up --exit-code-from test
