---
version: "3.3"
services:
  database:
    image: mariadb
    container_name: stormtask_database_container
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: mhYRrXUux5i7PmXLqmDuLrqEQ5tAQa
      MARIADB_DATABASE: stormtask_database
      MARIADB_USER: stormtask_user
      MARIADB_PASSWORD: vV4UbidqXzCj62pxiSsC8gnQTtNfcm
  test:
    image: stormtask_test_image
    container_name: stormtask_test_container
    depends_on:
      - database
    entrypoint:
      - "./wait-for.sh"
      - "stormtask_database_container:3306"
      - "--"
      - "go"
      - "test"
      - "./server/..."
      - "-cover"
      - "-parallel"
      - "1"
    environment:
      DATABASE_URL: stormtask_database_container
      DATABASE_USER: stormtask_user
      DATABASE_PASSWORD: vV4UbidqXzCj62pxiSsC8gnQTtNfcm
      DATABASE_NAME: stormtask_database
      JWT_SECRET_KEY: SgVkYp3s6v9y*B&E)H@McQfThWmZq4t7
      TOKEN_COOKIE_NAME: JWT_token
      BCRYPT_COST: 9
