version: "3.9"
services:
  lint:
    image: golangci/golangci-lint:v1.41.1
    container_name: stormtask_lint_container
    volumes:
      - ../server:/app
    working_dir: /app
    entrypoint:
      - "golangci-lint"
      - "run"