version: "3.3"
services:
  lint:
    image: golangci/golangci-lint:latest
    container_name: stormtask_lint_container
    volumes:
      - ../:/app
    working_dir: /app
    entrypoint:
      - "golangci-lint"
      - "run"